
 
site_name: John Telford - Topics


theme:
    
  name: material

  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# Repository
repo_name: gpt
repo_url: https://github.com/JohnTelford/gpt.git

# nav tree
nav: 
#
  - Home: 
    - Welcome: index.md

    - AI:
      - What is AI: what_is_ai.md
      - Neural Networks: neural_networks.md
      - Tensor Flow: tensor_flow.md
      - Singularity: ai_singularity.md
    
    # - GPT:
      - GPT: GPT.md
      - Topic Generalized Learning: generalized_learning.md
      - Forward Propagation: forward_propagation.md
      - Loss Calculation: loss_calculation.md
      - Back Propagation: backward_propagation.md
  
    - Python: python.md

    - Science:
        - Maxwell Equations: maxwell.md
        - Theory of Relativity: theory_of_relativity.md
        - Quantum Mechanics:
          - Introduction: quantum.md
          - Quantum Computers: quantum _computers.md
     
    - Markdown:
        - Math processing: markdown.md


    - Topic Block Chain: block_chain.md

plugins:
    - search:
      # - git-revision-date-localized:
      #   type: timeago
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true
  - attr_list
  - md_in_html 

  # - toc:
  #     permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: localhost:8001

copyright: Copyright &copy; 2023 John Telford
