
site_name: John Telford - GPT

theme:
  name: material

  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# nav tree
nav:
#
  # - Home:
  #   - GPT : index.md
  
  - Home: 
    - GPT Conversations: index.md

    - Topic AI:
      - What is AI: what_is_ai.md
      - GPT: GPT.md
      - Neural Networks: neural_networks.md
      - Tensor Flow: tensor_flow.md
      - Singularity: ai_singularity.md
    
    - Topic GPT:
      - Topic Generalized Learning: generalized_learning.md
  
    - Topic Python: python.md

    - Topic Science:
        - Maxwell Equations: maxwell.md
      
    - Topic Markdown:
        - Math processing: markdown.md

    - Topic Quantum Mechanics:
      - Introduction: quantum.md
      - Quantum Computers: quantum _computers.md

    - Topic Block Chain: block_chain.md

plugins:
- search:
  # - git-revision-date-localized:
  #   type: timeago
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.betterem
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences



