
site_name: John Telford - GPT

theme:
  name: material

  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:

    primary: teal
    accent: indigo
 


# nav tree
nav:
#
  # - Home:
  #   - GPT : index.md
  
  - Home: 
    - GPT Conversations: index.md
    - Topic GPT: GPT.md
    - Topic Python: python.md

    - Topic Science:
      - Maxwell Equations: maxwell.md
    
    - Markdown:
      - Math processing: markdown.md

    - Quantum Mechanics:
      - Introduction: quantum.md
      - Quantum Computers: quantum _computers.md




