
 
site_name: John Telford - Topics


theme:
    
  name: material

  features:
    - header.autohide
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# Repository
repo_name: gpt
repo_url: https://github.com/JohnTelford/gpt.git

# nav tree
nav: 
#
  - Topics Home: 
    - (Welcome): index.md
    - (Hype Curve): hype_curve.md

    - (Autonomous Vehicles): 
      - Autonomous Cars: ev/self_driving_cars.md
      - Autonomous Trucks: ev/self_driving_trucks.md
      - Autonomous Vehicles Video: ev/ev_video.md
      - Autonomous Vehicles Black Box: ev/ev_black_box.md

    - (AI):
      - What is AI: Topics/AI/what_is_ai.md
      - AI Hype Curve: Topics/AI/ai-hype-curve.md
      - ELIZA: Topics/AI/eliza.md
      - GPT: Topics/AI/GPT.md
      - Generalized Learning: Topics/AI/generalized_learning.md
      - Neural Networks: Topics/AI/neural_networks.md
      - Forward Propagation: Topics/AI/forward_propagation.md
      - Loss Calculation: Topics/AI/loss_calculation.md
      - Back Propagation: Topics/AI/backward_propagation.md
      - Parameters: Topics/AI/parameters.md
      - Tensor Flow: Topics/AI/tensor_flow.md
      - Singularity: Topics/AI/ai_singularity.md

    - (Electronics):
      - Nonlinear Modulation: Topics/Electronics/nonlinear_modulation.md
      - Software Defined Radio: Topics/Electronics/software_defined_radio.md

    - (Science):
      - Boson: Topics/Science/boson.md
      - Maxwell Equations: Topics/Science/maxwell.md
      - Neurons: Topics/Science/neutrino.md
      - Theory of Relativity: Topics/Science/theory_of_relativity.md
      - Space-Time: Topics/Science/space_time.md 
      - Quantum Mechanics: 
        - Introduction: Topics/Science/quantum.md
        - Quantum Computers: Topics/Science/quantum _computers.md
     
    - (Security): 
      - 2FA TOTP: 2fa_totp.md
      - Block Chain: block_chain.md


    - (Software):
      - Python: python.md
      - Markdown Math processing: markdown.md

    - (Misc): gpt_4_miscelanous/misc.md

plugins:
    - search:
      # - git-revision-date-localized:
      #   type: timeago
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true
  - attr_list
  - md_in_html
  - def_list

  # - toc:
  #     permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: localhost:8000

copyright: Copyright &copy; 2023 John Telford
