
 
site_name: John Telford - Topics


theme:
    
  name: material

  features:
    - header.autohide
    # - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# Repository
repo_name: gpt
repo_url: https://github.com/JohnTelford/gpt.git

# nav tree
nav: 
#
  - Home: 
    - Welcome: index.md
    - Hype Curve: hype_curve.md

    - (AI):
      - What is AI: Topics/AI/what_is_ai.md
      - ELIZA: Topics/AI/eliza.md
      - GPT: Topics/AI/GPT.md
      - AI Hype Curve: img/ai_hype.png
      - Large Language Model: Topics/AI/llm.md
      - Generalized Learning: Topics/AI/generalized_learning.md
      - Generative Pre-Learning Transform: Topics/AI/generative_pre_learning_transform.md
      - Neural Networks: Topics/AI/neural_networks.md
      - Forward Propagation: Topics/AI/forward_propagation.md
      - Loss Calculation: Topics/AI/loss_calculation.md
      - Back Propagation: Topics/AI/backward_propagation.md
      - Parameters: Topics/AI/parameters.md
      - Tensor Flow: Topics/AI/tensor_flow.md
      - Singularity: Topics/AI/ai_singularity.md

    - (Astronomy):
      - Neutrino: Topics/Astronomy/neutrino.md
      - Sun: Topics/Astronomy/sun.md

    - (Autonomous Vehicles): 
      - Autonomous Cars: Topics/Autonomous_Vehicles/self_driving_cars.md
      - Autonomous Trucks: Topics/Autonomous_Vehicles/self_driving_trucks.md
      - Autonomous Vehicles Video: Topics/Autonomous_Vehicles/ev_video.md
      - Autonomous Vehicles Black Box: Topics/Autonomous_Vehicles/ev_black_box.md
      - 5G - Autonomous Vehicles: Topics/Autonomous_Vehicles/5g.md

    - (Electronics):
      - Nonlinear Modulation: Topics/Electronics/nonlinear_modulation.md
      - Software Defined Radio: Topics/Electronics/software_defined_radio.md

    - (Health):
      - Why Do We Yawn: Topics/Health/yawn.md
      - What Is Cellulitis: Topics/Health/cellulitis.md
      - What is Pilonidal Cyst: Topics/Health/pilonidal.md
      - What is Quadriceps Rupture: Topics/Health/quadriceps.md

    - (Metaverse): Topics/Meta/metaverse.md

    - (Science / Physics):
      - Math: Topics/Science/Physics/physics_made_up.md
      - Maxwell Equations: Topics/Science/maxwell.md
      - Neutrino: Topics/Astronomy/neutrino.md
      - Theory of Relativity: Topics/Science/theory_of_relativity.md
      - Space-Time: Topics/Science/space_time.md 
      - Quantum Mechanics: 
        - Introduction: Topics/Science/Quantum_Mechanics/quantum.md
        - Quantum Computers: Topics/Science/Quantum_Mechanics/quantum _computers.md
        - Quantum Field Theory: Topics/Science/Quantum_Mechanics/quantum_field_theory.md
        - Boson: Topics/Science/Quantum_Mechanics/boson.md
     
    - (Security): 
      - 2FA TOTP: Topics/Security/2fa_totp.md
      - Block Chain: Topics/Security/block_chain.md
      - Cloudflare Warp: Topics/Security/cloudflare_warp.md


    - (Software):
      - Python: Topics/Software/python.md
      - Markdown Math processing: Topics/Software/markdown.md
      - NZB Files: Topics/Software/nzb_files.md
      - VScode: Topics/Software/vscode.md
      - Material for MkDocs: Topics/Software/material_for_mkdocs.md
      - Web Languages: Topics/Software/web_languages.md
      
    - (Telecom):
      - Cellular Networks: Topics/Telecom/cellular_networks.md
      - 4G: Topics/Telecom/4g.md
      - 5G: Topics/Telecom/5g.md
      - 6G: Topics/Telecom/6g.md

    - (Web): 
      - Browsers: Topics/Web/web_browser.md
      - Servers: Topics/Web/web_server.md

    - (UNIX):
      - UNIX: Topics/UNIX/unix.md
      - USENET: Topics/UNIX/usenet.md
      - macOS: Topics/UNIX/macos.md
      - Linux: Topics/UNIX/linux.md


plugins:
    - search:
    - git-revision-date-localized:
        type: date
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true
  - attr_list
  - md_in_html
  - def_list

  # - toc:
  #     permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: localhost:8002

copyright: Copyright &copy; 2023 John Telford
